config/routes.rb
Calendar::Application.routes.draw do
  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "home/index"
  devise_for :users
  get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  resources :events do
	  resources :images, only: [:create, :destroy, :index]
  end
  root :to => "home#index"
  get "calendar/index", :as => :user_root

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
  #attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/event.rb
# coding: utf-8
class Event < ActiveRecord::Base
  has_many :images
  has_event_calendar
  validates :name, :start_at, :end_at, :body,
	  presence: true
end

app/models/image.rb
class Image < ActiveRecord::Base
  validates :title, presence: true;
  belongs_to :event
  mount_uploader :title, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  
	def index
	    if !user_signed_in?
	        redirect_to new_user_session_path
	    else
		@month = (params[:month] || (Time.zone || Time).now.month).to_i
		@year = (params[:year] || (Time.zone || Time).now.year).to_i

		@shown_month = Date.civil(@year, @month)

		@event_strips = current_user.events.event_strips_for_month(@shown_month)
	    end
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
            if !user_signed_in?
                redirect_to new_user_session_path
            else
		#@user = current_user
		@events = current_user.events.find(:all, :order => "start_at")
	    end
	end
	
	def new
            if !user_signed_in?
                redirect_to new_user_session_path
            else
		@event = Event.new
	    end
	end

	def show
            if !user_signed_in?
                redirect_to new_user_session_path
            else
		@event = Event.find(params[:id])
		@events = Event.find(:all, :order => "start_at DESC")
	    end
	end

	def create
		@event = current_user.events.new(params[:event].permit(:name, :start_at, :end_at, :body))
		if @event.save
			redirect_to calendar_path
		else
			render 'new'
		end
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to events_path
	end

	def edit
		@event = Event.find(params[:id])
	end

	def update
		@event = Event.find(params[:id])
		@user.update(user_params)	
		redirect_to calendar_path
	end
		
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
        def create
                @event = Event.find(params[:event_id])
		@image = @event.images.create(image_params)
                redirect_to  event_path(@event.id)
        end
        
	def destroy
                @image = Image.find(params[:id])
                @image.destroy
                redirect_to event_path(params[:event_id])
        end

  private
        def image_params
                params[:image].permit(:title, :body)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end
  
  # custom options for this calendar
  def event_calendar_opts
    { 
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.prev_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>"    }
  end

  def event_calendar
    # args is an argument hash containing :event, :day, and :options
    calendar event_calendar_opts do |args|
      event = args[:event]
      %(<a href="/events/#{event.id}" title="#{h(event.name)}">#{h(event.name)}</a>)
      #%(<a href="/calendar" title="#{h(event.name)}">#{h(event.name)}</a>)
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/calendar/index.html.erb
<!-- Probably move the stylesheet to you layout. Also make sure you include the javascript. -->
<div class="block">
	 <div class="secondary-navigation"> 
		 <ul class="wat-cf">	
			 <li class="active"><a href="/calendar">Calendar</a></li>
			 <li><a href="/events/new">New Memory</a></li>
			 <li><a href="/events/">Events</a></li>
		 </ul>
	 </div>
	 <div class = "content">
		 <h2 class="title">Calendar</h2>
		 <div class = "inner">
			<%= stylesheet_link_tag "event_calendar" %>
			<p><%= raw(event_calendar) %></p>
		</div>
	 </div>
</div>
<div class = "content">
	<% content_for :sidebar do %>	
		<div class="block">
			<h2>Sidebar</h2>
		</div>
<% end %>
</div>

app/views/events/index.html.erb
<div class="block">
	<div class="secondary-navigation">
		<ul class="wat-cf">
			<li><a href="/calendar">Calendar</a></li>
			<li><a href="/events/new">New Memory</a></li>
			<li class="active"><a href="/events/">Events</a></li>
		</ul>
	</div>
	<div class = "content">
		<h2 class="title">Events</h2>
		<div class = "inner">
			<table class="table">
				<tr>
					<th>Event Name</th>
					<th>Start</th>
					<th>End</th>
					<th>Details</th>
				</tr>
				<% @events.each do |event| %>
				<tbody>
					<tr>
						<td><%= link_to event.name, controller:"events", action:"show", id:event.id %></td>
						<td><%= event.start_at.strftime("%Y-%m-%d") %></td> 
						<td><%= event.end_at.strftime("%Y-%m-%d") %></td> 
						<td><%= event.body %></td>
						<td><%= link_to "[DELETE]", event_path(event.id), method: :delete, data: { confirm: "are you sure?" } %></td>
					</tr>
				</tbody>
				<% end %>
			</table>	
		</div>
	</div>
</div>

app/views/events/new.html.erb
<div class="block">	
	<div class="secondary-navigation">
		<ul class="wat-cf">
			<li><a href="/calendar">Calendar</a></li>
			<li class="active"><a href="/events/new">New Memory</a></li>
			<li><a href="/events/">Events</a></li>
		</ul>
	</div>
	<div class = "content">
		<h2 class = "title">New Schedule</h2>
		<div class = "inner">
			<div class = "form">
				<%= form_for @event do |f| %>
					<% if @event.errors.any? %>
						<p>	
						<div class="flash">
							<div class="message error">
								<p>誤りがあります:入力がされていない？日付が誤ってる？</p>

							</div>
						</div>
						</p>
					<% end %>
				<div class = "group">  
					<%= f.label :"New Event", :class => "label" %>
					<%= f.text_field :name, :class => "text_field"%>
				</div>
				<div class = "group">
					<%= f.label :"Start Date", :class => "label"%>
					<%= f.date_field :start_at %>
				</div>
				<div class = "group">
					<%= f.label :"End Date", :class => "label"%>
					<%= f.date_field :end_at %>
				</div>
				<div class = "group">
					<%= f.label :"Details", :class => "label"%>
					<%= f.text_area :body, :class => "text_area" %>
				</div>
				</div>
					<div class = "submit">	
					<%= f.submit %>
				</div>
				<% end %>
			</div>
	</div>
</div>

app/views/events/show.html.erb
<%= javascript_include_tag "jquery", "jquery_ujs" %>
<h2 class="title"><%= @event.name %></h2>
<h3 class="date"><%= @event.start_at.to_date %> ~ <%= @event.end_at.to_date %></h3>
<h3 class="details"><%= @event.body %></h3>
<div class = "inner">
<%- if false -%>
	<table class="table">
			<tr>
				<th>Details</th>
				<th></th>
			</tr>
		<tbody>
			<tr>
				<td><%= @event.body %></td>
				<td><%= link_to "[DELETE]", event_path(@event.id), :method => :delete %></td>
			</tr>
		</tbody>
	</table>
	<% @event.images.each do |image| %>
		　<% if image.title? %>
			　<p><%= image_tag image.title.thumb.url %>
		　<% else %>
		　　<%= image_tag 'noimage.gif' %>
		　<% end %>
			  <%= link_to "[DELETE]", event_image_path(image.event_id, image.id), :method => :delete %>
			  </p>
	<% end %>
	<%= form_for [@event, @event.images.build] do |f| %>
	<p><%= f.file_field :title %></p>
	<%= f.submit %>
	<% end %>
<%- end -%>
</div>
<div class = "sidebar">
	<div class = "block">
		<% content_for :sidebar do %>
		<div class = "block">
			<h3>Add Images</h3>
				<div class = "content">
					<%= form_for [@event, @event.images.build] do |f| %>
						<p><%= f.label :"Image Description" %></p>
						<p><%= f.text_area :body, :size=>"40x5"%></p>
						<p><%= f.file_field :title %></p>
						<p><%= f.submit %></p>
					<% end %>
				</div>
		</div>
		<div class = "block">
			<h3>Other Events</h3>
			<ul class = "navigation">
				<% @events.each do |event| %>
					<li>
					<a href="/events/<%= event.id %>"><%= event.name %></a>
					</li>
				<% end %>
			</ul>
		</div>
		<% end %>
	</div>
</div>
<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
    <script type="text/javascript">
    // All images need to be loaded for this plugin to work so
    // we end up waiting for the whole window to load in this example
    $(window).load(function () {
        $(document).ready(function(){
            collage();
            $('.Collage').collageCaption();
        });
    });
    // Here we apply the actual CollagePlus plugin
    function collage() {
        $('.Collage').removeWhitespace().collagePlus(
            {
                'fadeSpeed'     : 2000,
                'targetHeight'  : 200,
                'effect'        : 'effect-4',
                'direction'     : 'vertical'
            }
        );
    };
    // This is just for the case that the browser window is resized
    var resizeTimer = null;
    $(window).bind('resize', function() {
        // hide all the images until we resize them
        $('.Collage .Image_Wrapper').css("opacity", 0);
        // set a timer to re-apply the plugin
        if (resizeTimer) clearTimeout(resizeTimer);
        resizeTimer = setTimeout(collage, 200);
    });
    </script>
</head>
<body>
	<table class="table">
			<tr>
				<th>Images</th>
			</tr>
		<tbody>
			<tr>
				<td>
					<section class="Collage effect-parent">
						<% @event.images.each do |image| %>
							<% if image.title? %>
								<div class="Image_Wrapper" data-caption="<%= image.body %>">
									<a><%= image_tag image.title.url %></a>
								</div>
							<% end %>
						<% end %>
					</section>
				</td>
			</tr>
		</tbody>
	</table>
</body>
</html>

app/views/home/index.html.erb
<h1>TOP</h1>
<% if user_signed_in? %>
	<%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
<% else %>
	<%= link_to "ログイン", new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<%= javascript_include_tag "jquery", "jquery_ujs" %>
<!DOCTYPE html>
<html>
<head>
  <title>My Memories</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/default/style", "web-app-theme/override", :cache => true %>
  <%= javascript_include_tag :defaults, :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
	    <h1><a href="/calendar">My Memories</a></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
		<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf"></ul>
      </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> Takeshi Industry.</p>
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
  <%= stylesheet_link_tag "examples", "transitions", :media => "all" %>
  <%= javascript_include_tag "jquery.collagePlus", "jquery.removeWhitespace", "jquery.collageCaption" %>
</body>
</html>